### ISSUE TITLE
Unable to issue access tokens where the audience has an spn: prefix

### ISSUE THREAD

**Issue by rombert** [AzureAD/microsoft-authentication-library-for-java#183]
I am using msal4j to retrieve access tokens that will be used with a kubernetes cluster running on Azure. The code I am using is

```
        return PublicClientApplication.builder(clientId)
            .build().acquireToken(RefreshTokenParameters.builder(new HashSet<>(), refreshToken).build());
```

The access token comes back with a audience claim of the form `"aud": "$GUID"`. However, the infrastructure requires that we send them in the form of `"aud": "spn:$GUID"`. There is a long set of discussions related to this, e.g. https://github.com/kubernetes/kubernetes/pull/86412 . 

I would like to be able to issue such an access token, but I did not find a way to do that with this library. I am using t

How can I issue an access token whose `aud` claim includes an `spn:` prefix?

**Comment by rombert** [comment]
FWIW I am able to generate such tokens by manually hitting https://login.microsoftonline.com/${TENANT_ID}/oauth2/token and setting api-version=1.0 .

However, I think MSAL uses a different entry point, and I also found no way of passing arbitrary values for the payload.

**Comment by sangonzal** [comment]
@rombert A couple of notes: 
- Instead of using `RefreshTokenParameters`, you should consider using `SilentParameters`. This way you offload the refreshing of refresh tokens to MSAL. Curious as where to you are grabbing the refresh token from, given that it's not exposed in `IAuthenticationResult`

-  My understanding is that this format of access tokens is a legacy format not supported in v2 of the Azure AD API. So you can get a token with this format by going to "https://login.microsoftonline.com/${TENANT_ID}/oauth2/token" but not at"https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token", which is the endpoint that this library communicates with. All to say, this will not work with any of the MSALs. It seems that  Kubernetes merged a PR to update token validation on their end to support access tokens in the new format. Any idea when this update will hit your cluster?

**Comment by rombert** [comment]
Thanks for the information @sangonzal 

1. I am obtaining the refresh token through a different workflow, and it's considered as configuration.
1. Thank you for the pointer to `SilentParameters`, I will explore that
1. The cluster update is not something I see in the near future, given the backwards compatibility implications. However, I did hand-code an alternative token provider for my application which uses the legacy entry point, and I will switch to the MSAL-based one once I am able to.

I see no further action here, so closing.
