### ISSUE TITLE
How to get access token using azure username & Password.

### ISSUE THREAD

**Issue by imshreya** [AzureAD/microsoft-authentication-library-for-java#193]
I want to authenticate using on username & password.

**Comment by sangonzal** [comment]
Here is a sample showing how to acquire a token using username & password- https://github.com/Azure-Samples/active-directory-java-native-headless-v2 

Keep in mind that username-password is not recommended due to reasons explained here -  [UsernamePassword docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-acquire-token?tabs=java#username-and-password)

Depending on your scenario, I would recommend taking a look at device code flow or acquire token interactive flow. Take a look a this page, it will explain multiple ways of acquiring a token - https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Acquiring-Tokens
