### ISSUE TITLE
No Default TokenCache available

### ISSUE THREAD

**Issue by MBurchard** [AzureAD/microsoft-authentication-library-for-java#207]
I have this Code:

	public Optional<AccessToken> getAccessToken() {
		final IClientSecret secret = ClientCredentialFactory.createFromSecret(clientSecret);
		try {
			final ConfidentialClientApplication cca =
					ConfidentialClientApplication.builder(clientId, secret).authority(authority).build();

			final IAuthenticationResult iAuthenticationResult =
					acquireTokenSilently(cca).orElseGet(() -> acquireToken(cca));

			return Optional.of(new AccessToken(iAuthenticationResult.accessToken(),
					iAuthenticationResult.expiresOnDate()));
		} catch (final Throwable th) {
			LOG.error("", th);
		}
		LOG.warn("No access token available for client {} and authoriy {}", clientId, authority);
		return Optional.empty();
	}

	private Optional<IAuthenticationResult> acquireTokenSilently(
			final ConfidentialClientApplication cca) throws Throwable {
		final IAuthenticationResult result;
		try {
			final SilentParameters silentParameters = SilentParameters.builder(scopes).build();

			// try to acquire token silently. This call will fail since the token cache does not
			// have a token for the application you are requesting an access token for
			return Optional.ofNullable(cca.acquireTokenSilently(silentParameters).join());
		} catch (final CompletionException ex) {
			if (ex.getCause() instanceof MsalClientException) {
				LOG.debug(ex.getMessage());
			} else {
				throw ex.getCause();
			}
		}
		return Optional.empty();
	}

	private IAuthenticationResult acquireToken(
			final ConfidentialClientApplication cca) {
		final ClientCredentialParameters parameters =
				ClientCredentialParameters.builder(scopes).build();
		return cca.acquireToken(parameters).join();
	}

Expected Behaviour: After first successful `acquireToken` the Token is in the Cache. The next request to `acquireTokenSilently` should get the token from the cache, that previously was put to the cache. But that does not happen.

I was unable to find a way to set a custom cache. Looking at the samples at https://docs.microsoft.com/de-de/azure/active-directory/develop/scenario-desktop-acquire-token?tabs=java I had no luck to find out, how to implement something like TokenCacheAspect.

Please improve the documentation.

Or better, please implement a default token cache, that is in memory something like the Caffeine cache: https://github.com/ben-manes/caffeine

**Comment by sangonzal** [comment]
@MBurchard "After first successful acquireToken the Token is in the Cache. The next request to acquireTokenSilently should get the token from the cache, that previously was put to the cache"  This should be the expected behavior. Could you confirm that there is a token in the cache after making the first `acquireToken` call? If you are debugging, should be able to look at the tokenCache field on the client application object. Remember that you should be passing in the same scope into `acquireTokenSilently` that you passed into `acquireToken`

MSAL comes with a default in-memory cache. TokenCacheAspect is used to provide a way to write and read changes to a file. The way this is done is through two hooks -  `beforeCacheAccess()` and `afterCacheAccess`. 

 `beforeCacheAccess()` is called by MSAL before it access the cache, to make sure that you have the latest changes in memory. (this is in the case that multiple applications are writing to the same cache file).

 `afterCacheAccess`  is called after it access the cache, to write the latest changes to the file. 

Here is a naive implemetation of the `TokenCacheAspect`: https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/src/samples/cache/TokenCacheAspect.java. This should give you a general idea of how you should implement it.

**Comment by MBurchard** [comment]
Thank you for the answer and you are absolutely right, there is a default cache implementation that works fine.
As you can see in my method `getAccessToken` the `ConfidentialClientApplication` was newly create on every usage. I fixed that ...

    public class ConfidentialClientAuthProvider implements IAuthenticationProvider {
        private ConfidentialClientApplication cca;
