### ISSUE TITLE
[Feature Req] Make MSAL clients accept Async Http Client and Executor 

### ISSUE THREAD

**Issue by g2vinay** [AzureAD/microsoft-authentication-library-for-java#220]
Currently, MSAL clients accept Executor Service to execute auth requests.
 
Ask: 
1. Would it be possible to make MSAL clients accept Executor instead of Executor Service ?

Issue:
With current implementation, Identity customers who implement their custom executors will need to implement the Executor Service interface and the extra API that comes with it (or leave them empty that will impact their code readability).
 
 
Ask:
2. Would it be possible for MSAL clients to accept an async HTTP client ?
 
Currently, our Identity library by default passes a Netty client to the MSAL clients, but it gets used by MSAL synchronously and to make it asynchronous CompletableFutures are used. (Correct me if I am wrong here).
But, Netty has its own thread pool, if MSAL could just use the Netty client asynchronously, then there will not be a need for CompletableFutures to be created for asynchronous execution.

If we get this as a feature, then we will potentially not need # 1 (above) to be exposed to our users.

**Comment by SomkaPe** [comment]
1.
The ExecutorService interface contains methods for controlling the progress of the tasks and managing the termination of the service.

It is quite important to support graceful termination of service, because abrupt termination of tasks submitted to it might lead to serious errors. For example, if execution of MSAL API will be terminated while writing to the cache, cache corruption might happen.

So, by using ExecutorService service in MSAL API we suggest that implementation with graceful termination support should be used.

2. MSAL API execution is a bit more complicated than one HTTP call. 
During execution I/0 operations + multiple network calls could be executed, so the whole thing should be executed asynchronously.

Exposure of client provided ExecutorService is important extensibility point.
And it is optional.

**Comment by navyasric** [comment]
The question has been answered and followed up in email.
