### ISSUE TITLE
Serialization failed for IAuthenticationResult

### ISSUE THREAD

**Issue by abhijeetsaxena7** [AzureAD/microsoft-authentication-library-for-java#292]
I am trying to use spring jdbc session and I want to store the IAuthenticationResult object returned on calling ClientConfidentialParamter.acquireToken() method. However, I keep getting the error that IAuthenticationResult cannot be serialized. I looked into it and realized that IAuthenticationResult is an interface. AuthenticationResult is the subclass but I cannot use it as its visibility is default in the package and I dont have access to it. Is there anyother way to serialize/deserialize IAuthenticationResult data?

**Comment by Avery-Dunn** [comment]
Hello @abhijeetsaxena7 : Unfortunately, I don't think there's a quick way to serialize IAuthenticationResult/AuthenticationResult objects themselves. We plan on discussing this issue, and make serialization of these objects more straightforward in a future update.

For now though, the best workaround I can suggest is to extract the data you need from the IAuthenticationResult into a custom object, and serialize that.

**Comment by idg-sam** [comment]
Maybe we should add a demonstration in our samples for this.

**Comment by abhijeetsaxena7** [comment]
> Hello @abhijeetsaxena7 : Unfortunately, I don't think there's a quick way to serialize IAuthenticationResult/AuthenticationResult objects themselves. We plan on discussing this issue, and make serialization of these objects more straightforward in a future update.
> 
> For now though, the best workaround I can suggest is to extract the data you need from the IAuthenticationResult into a custom object, and serialize that.

I create my own class for and stored tokenCache and account details and then serialized that class.

**Comment by Avery-Dunn** [comment]
Hello @abhijeetsaxena7 : Glad you were able to work around this issue. We plan on making IAccount serializable in the next update, to help with things like setting up .acquireTokenSilently() calls and searching through the results of .getAccounts(). 

However, we don't plan on making IAuthenticationResult serializable, as we don't think there is a good use-case for that: all of the token info they contain can be found in the token cache (which is serializable), and once IAccount is serializable there'll be no reason to store the IAuthenticationResult instead of the IAccount and the token cache.

Could you share a bit of your use case here? Was there some specific need/convenience to store IAuthenticationResult objects in session rather than the token cache, and would the ability to serialize/store the IAccount from an auth result along with the token cache solve that issue?

**Comment by abhijeetsaxena7** [comment]
The msal java Web app sample stored the entire IauthenticationResult object in the session. After carefully studying the code, I realised it was misleading and corrected my storage options. I am now only storing IAccount and Token cache.
