### ISSUE TITLE
Why no concent page display when use authorization code flow to acquire access token

### ISSUE THREAD

**Issue by moarychan** [AzureAD/microsoft-authentication-library-for-java#339]
I expect to use APIs in '**APIs my organization uses**', there's an API that does not require admin consent, I did not grant the admin consent.
![image](https://user-images.githubusercontent.com/19926623/105017841-3adf6f00-5a7f-11eb-9376-a514ff989344.png)

when I acquire the access token for this API, no consent page displayed, is this normal?

Or all the APIs in '**APIs my organization uses**' tab and in '**My APIs**' tab, the user consent page will not appear when using OAuth2 authorization code flow to apply for an access token.

Please help to confirm, or please tell me when the user consent age will appear? Many thanks!

**Comment by sangonzal** [comment]
@moarychan Did you by chance grant consent to the whole tenant? Theres a button right above the API permissions that says "Grant Admin Consent for <Name> Tenant". Have you consented to this permission previously with the same user?

**Comment by moarychan** [comment]
Not consented yet, I hope users can see the authorized page, which users can choose to agree, and then return the access token. I used permission 'teams', this is not required by Admin consent.

**Comment by sangonzal** [comment]
> I read the 'teams' permission description, it means not required by Admin consent, then it can be consented by the user. Is that correct?

Yes I believe that is the case.

**Comment by sangonzal** [comment]
@moarychan Can you verify if the user you are using to test has consented to that scope before? You can go to the app registration on the portal, "API Permissions" tab, and click on "Enterprise application"
![EnterpriseApplications](https://user-images.githubusercontent.com/35743865/114466373-0676dd00-9bae-11eb-8081-b70d54619c59.PNG)
. 

Here you can click on "User Consent" and see if the user has consented to this scope before. If so, that's why you're not being asked to consent.

**Comment by sangonzal** [comment]
Closing issue as I never heard back. Feel free to reopen if you continue having issues.
