### ISSUE TITLE
Add support to Azure FIHR Api by adding to "resource" parameters and empty scope

### ISSUE THREAD

**Issue by DevWantJustHaveFun** [AzureAD/microsoft-authentication-library-for-java#359]
I want to obtain an access token from AAD to authenticate against Azure FIHR Api
According to the documentation: https://docs.microsoft.com/en-us/azure/healthcare-apis/access-fhir-postman-tutorial#obtaining-an-access-token

I successfully get a token using this curl command:

```
curl -v -X POST "https://login.microsoftonline.com/${tenant_id}/oauth2/token" -d "client_id=${client_id}&client_secret=${client_secret}&grant_type=client_credentials&resource=https://{tenant_fihr_api}.azurehealthcareapis.com"
```

But how to use acquire a token using the "ConfidentialClientApplication" without scope and without the "resource" parameters ?

**Comment by sangonzal** [comment]
@DevWantJustHaveFun in your example, you are targeting the AAD v1 endpoint. MSAL only support the AAD v2 endpoint. This [document](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/active-directory/azuread-dev/azure-ad-endpoint-comparison.md) outlines the differences in between both, but in your case, the biggest is that v1 uses resources while v2 uses scopes. 

What happens if you update your curl command to: 

`curl -v -X POST "https://login.microsoftonline.com/${tenant_id}/oauth2/token/v2.0" -d "client_id=${client_id}&client_secret=${client_secret}&grant_type=client_credentials&scope=https://{tenant_fihr_api}.azurehealthcareapis.com/.default"`

**Comment by DevWantJustHaveFun** [comment]
@sangonzal thanks a lot for your response, so finally the issue is the [documentation](https://docs.microsoft.com/en-us/azure/healthcare-apis/fhir/access-fhir-postman-tutorial#obtaining-an-access-token) was not clear for me.

With your help I was able to use ConfidentialClientApplication to call the fhir api, here an example:

 ```
final String TENANT_ID = "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx";
final String CLIENT_ID = "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx";
final String CLIENT_SECRET = "my_secret";
final String AUTHORITY = "https://login.microsoftonline.com/" + TENANT_ID;
final String TENANT_FHIR_NAME = "my_fhir_tenant";
final String TENANT_FHIR_URL = "https://" + TENANT_FHIR_NAME + ".azurehealthcareapis.com"

final ConfidentialClientApplication client = ConfidentialClientApplication
                  .builder(CLIENT_ID, ClientCredentialFactory.createFromSecret(CLIENT_SECRET))
                  .authority(AUTHORITY)
                  .build();

final Set<String> scopes = Set.of(TENANT_FIHR_URL + "/.default");
final ClientCredentialParameters parameters = ClientCredentialParameters.builder(scopes).build();
final String authenticationToken = client.acquireToken(parameters).join().accessToken();

WebClient webClient = WebClient.builder().baseUrl(TENANT_FIHR_URL).build();

final String response = webClient
.get()
.uri(uriBuilder -> uriBuilder
        .path("/Patient/{patientId}")
        .build(patientId))
.headers(httpHeaders -> httpHeaders.setBearerAuth(authenticationToken))
.retrieve()
.bodyToMono(String.class)
.block();
```
