### ISSUE TITLE
JWT claims are not getting updated after token refresh using MSAL4J with B2C webapp

### ISSUE THREAD

**Issue by hemant7737** [AzureAD/microsoft-authentication-library-for-java#421]

**Comment by hemant7737** [comment]
Using custom policy(B2C) for signup or sing in with azure. 
While Sing In, In the custom flow we get some data via REST API and update the response in jwt claims.
After successfully sign in when we invoke below MSAL4J library method to refresh the token the above flow does not execute and we did not get updated data. It just update the "iat","exp" claims of the JWT.

Below is the code for getting refresh token silently.
```
    IAuthenticationResult getAuthResultBySilentFlow(HttpServletRequest httpRequest, String scope) throws Throwable {
        IAuthenticationResult result = AuthHelper.getAuthSessionObject(httpRequest);

        IAuthenticationResult updatedResult;
        ConfidentialClientApplication app;
        try {
            app = createClientApplication();
            Object tokenCache = httpRequest.getSession().getAttribute("token_cache");
            if (tokenCache != null) {
                app.tokenCache().deserialize(tokenCache.toString());
            }

            SilentParameters parameters = SilentParameters.builder(
                    Collections.singleton(scope),
                    result.account()).forceRefresh(true).build();

            CompletableFuture<IAuthenticationResult> future = app.acquireTokenSilently(parameters);

            updatedResult = future.get();
        } catch (ExecutionException e) {
            throw e.getCause();
        }

        if (updatedResult == null) {
            throw new ServiceUnavailableException("authentication result was null");
        }

        //update session with latest token cache
        storeTokenCacheInSession(httpRequest, app.tokenCache().serialize());

        return updatedResult;
    }
```

Would like to pay thanks in advance for any resolution.

**Comment by Avery-Dunn** [comment]
Hello @hemant7737 : Just to be clear, how exactly are you trying to refresh the token? The code you posted seems to be from one of our samples but with `forceRefresh(true)` added, and you're just calling it whenever you want to force a token to refresh, right?

As for your question, what claims are you expecting to be different after a refresh? You say you're using a custom policy during sign up/sign in, so are you trying to change some things in a user's profile during sign up, and they aren't being reflected after the refresh? If so, some data takes time to propagate in Azure, so if you're forcing a refresh immediately after making the change/getting the original token then it could simply be that Azure hasn't updated the info by the time you refreshed.

**Comment by hemant7737** [comment]
Hi @Avery-Dunn : Thanks you for the replying.

I have tried with updating the user's profile(given_name) at azure portal and then tried to refresh the token with my Java app after 1-2 minute. In Java app it did not reflect the updated "given_name".
Even I have tried both option with ``` forceRefresh(true) ``` and without but still it did not work.

Adding some snapshot for your reference: 

**Updated given name on azure portal**

![image](https://user-images.githubusercontent.com/29993655/126249237-dfad9377-9fcb-458d-ac83-49dbd88f0bd7.png)


**After Token Refresh**

![image](https://user-images.githubusercontent.com/29993655/126249563-dd89b255-9b47-4562-a08b-aac586c4f5d0.png)

**Comment by Avery-Dunn** [comment]
@hemant7737 : So you get a token for a user, then manually change that user's name in Azure, and then refresh the token, right? If so, I'm able to occasionally replicate this issue if I try to refresh after 1-2 minutes, but for me the name is always updated after waiting more than 3-5 minutes. 

Many changes in Azure aren't immediately available, so does this still happen if you wait longer? At least 5 or 10 minutes, or even an hour (when the token would naturally expire)? I haven't been able to find any documentation from the Azure folks about how quickly data gets updated, but the issue may simply be that you're trying to refresh the token too quickly.

**Comment by hemant7737** [comment]
Hi @Avery-Dunn 

After successfully logged in I waited for 10-15 minutes and then tried to refresh, Still did not get the expected result. 
I again waited for 1 Hour approximately  but this time it redirected me to login page and asked to login again with username and password.

**Comment by Avery-Dunn** [comment]
@hemant7737 : You said you were using B2C, right? I haven't done much with B2C so I don't know for sure, but maybe the name info is coming from somewhere other than Azure. Does this behavior happen with other claims, or just the name? If you change the email address, add/remove that user from groups or roles, or something else like that, does this behavior still happen?

Also, does this only happen when refreshing a token, or does that info just never change? In other words, if you get a token using some flow, change the name in Azure, then get a fully new token (not through the silent flow/refreshing) is the name still the same or is it correctly updated?

**Comment by hemant7737** [comment]
Hi @Avery-Dunn : Could you please help or assign the person who is dealing with such issues or has experience with B2C?

As I don't want to logout and relogging again as per our scenario. Want to go through the silent flow/refreshing.

**Comment by Avery-Dunn** [comment]
@hemant7737 : I've had a chance to test some things with a B2C account and I have some more ideas on what might be going on.

As I said before, the name might be coming from somewhere else than the Azure user. Is the user you're testing with a personal Microsoft account (like @outlook.com, or a company/school domain, or something), or is it user created in Azure (i.e., @yourtenant.onmicrosoft.com)? If it's the personal Microsoft account, I believe the name is coming the settings wherever that account was made instead of what you're changing in Azure. To give an example of the difference, here's the settings from the entry in the list of Users in my B2C tenant (similar to the screenshot you posted):
![image](https://user-images.githubusercontent.com/62066438/127043928-d21d4133-9f23-4bf5-908b-9db4c11e6408.png)

If the tokens were pulling info from Azure, then my name should be populated with 'Avery B2C Test' or 'Avery Dunn Test 1'. However, in my personal Microsoft account settings in Outlook, I set it to 'Avery Dunn Test 2':
![image](https://user-images.githubusercontent.com/62066438/127044159-c753b4d0-7099-4180-8d1d-5d6793b4c416.png)

That 'Avery Dunn Test 2' is what my tokens are being populated with:
![image](https://user-images.githubusercontent.com/62066438/127044359-4be6b674-c23d-4685-baf1-f42af5f5cf7a.png)

If I edit that name in Outlook, it also gets reflected in the refreshed tokens in a minute or less.

So, where did you make the account you've been testing with? If you [made the user in Azure](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/add-users-azure-active-directory) and it has an @yourTenant.onmicrosoft.com style email/name, then I can't reproduce the issue and am not sure why it's happening to you. Otherwise, if you created the user somewhere else (such as Outlook), then try changing the name there and see if the change shows up in refreshed tokens.

**Comment by hemant7737** [comment]
@Avery-Dunn : We have made account as B2C user.. B2C users can sign in using an email address or a unique username.
As I mentioned earlier we are using the custom policy flow for sign up and sing in the user.
When we logged in using MSAL4J with my Java web app that is similar to the provided sample. If  We change anything related to the user profile at Azure portal and tried to refresh token using acquireTokenSilently() from the Java App. It did not update details in received token but its generation time and expiry time gets updated. But if I logged out and log in again then I get the updated profile.

So here my question is like, What happens under the hood when we call "acquireTokenSilently()"? Could you please help me to understand.

**Comment by nickgmicrosoft** [comment]
@JasSuri  can you take a look

**Comment by JasSuri** [comment]
`AcquireTokenSilent()` with `forceRefresh(true)`, will force the MSAL.js library to acquire a new access token using the refresh token, even if the current access token is valid. Under the hood, MSAL.js performs the following [refresh token grant](https://docs.microsoft.com/en-us/azure/active-directory-b2c/openid-connect#refresh-the-token).

The behavior described here in this issue is expected. Azure AD B2C does not refresh the claim set issued into a newly minted token during the refresh token flow.
