### ISSUE TITLE
package private abstract base classes with public members

### ISSUE THREAD

**Issue by chrisbetz** [AzureAD/microsoft-authentication-library-for-java#474]
Using version 1.11.2, Java 17, Clojure 1.11.0-beta1.

Due to [Clojure issue 'Cannot resolve public generic method from package-private base class'](https://clojure.atlassian.net/browse/CLJ-1243), the classes `com.microsoft.aad.msal4j.AbstractClientApplicationBase` and 
`com.microsoft.aad.msal4j.AbstractClientApplicationBase$Builder` make it hard to use msal4j with Clojure.

An easy fix would be to make the two classes `public`. I was not able to test this, unfortunately. Let me know if you need some Clojure test project to check.

Thanks!

**Comment by Avery-Dunn** [comment]
Hello @chrisbetz : I don't have any experience with Clojure, so just to clarify: 
- Is this issue happening when trying to use a method inherited from `AbstractClientApplicationBase`, like what `ConfidentialClientApplication` or `PublicClientApplication` objects would have? 
  - If so, is it all inherited methods or do overriden methods not cause this error?
- Or is it happening when trying to call the methods in `AbstractClientApplicationBase` directly, such as when you make an object like `AbstractClientApplicationBase clientApplication;` and later call a method through that 'clientApplication' object?
  - If so, if you explicitly create `ConfidentialClientApplication` or `PublicClientApplication` objects instead of `AbstractClientApplicationBase` can you use those methods?

This is a fairly common pattern in Java, and I'm sure we use it more than just in the client application classes so even if we make this abstract class public you'll probably just run into the issue again somewhere else. However, since this is valid Java I'd be surprised if there wasn't some workaround for this in Clojure, especially since that issue you linked was created all the way back in 2013.

**Comment by chrisbetz** [comment]
Hi @Avery-Dunn, (sorry, been on sick leave for two days)

thanks for caring:  It's more the first option you're outlining, but I'll try to explain in detail.

I'm following the Java steps in [Daemon app that calls web APIs - code configuration > Instantiate the confidential client application with a client secret](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-daemon-app-configuration?tabs=java#instantiate-the-confidential-client-application-with-a-client-secret), just trying to transfer that to Clojure.

So, I'm creating a `com.microsoft.aad.msal4j.ConfidentialClientApplication$Builder` using the `ConfidentialClientApplication.builder` method. That's working and I get a Builder object (let's call it `builder`).

On that `builder` object, I'm trying to invoke the `authority` method.

1. To do so, Clojure has a "convinience" mechanism for [member access](https://clojure.org/reference/java_interop#_member_access). When I'm trying to do this, I run into the problem described in that Clojure issue [CLJ-1243](https://clojure.atlassian.net/browse/CLJ-1243), as Clojure is not able to "identify" the right method to call.

2. There's another possibility to call Java methods in Clojure using reflection: Find the method object and invoke that. When I'm doing that, I'm able to identify the right `authority` method using the `.getMethods` method on the `com.microsoft.aad.msal4j.ConfidentialClientApplication$Builder` class.
When I'm trying to invoke that method, I run into another problem:
`Execution error (IllegalAccessException) at jdk.internal.reflect.Reflection/newIllegalAccessException (Reflection.java:392).
class clojure.lang.Reflector cannot access a member of class com.microsoft.aad.msal4j.AbstractClientApplicationBase$Builder with modifiers "public"`. I can work around that problem by making the `authority` method I found "accessible" by calling `setAccessible` on the `authority` method object first.

So, I can work it out, but it's unbelievably hard. It's something I never encountered before (and I create an Apache Spark abstraction and a Neo4j abstraction for Clojure), and both problems originate from the choice to inherit _public_ methods from a _package visible_ class. Obviously that's working in Java, but it's not a common pattern (at least I did not cross anything like that in the last ten years ;)).

So, I just followed the class names to identify `com.microsoft.aad.msal4j.AbstractClientApplicationBase` and
`com.microsoft.aad.msal4j.AbstractClientApplicationBase$Builder` as being potentially problematic in the Clojureverse.

Making these two abstract classes public (instead of package-visible) would ease the life of Clojure users of the msal4j lib with little to no impact on any other developers. (Ok, someone could inherit/extend from these abstract classes outside of the package, but I can't see negative impact from that).


I hope that clarifies things, and I'm happy to assist with further explanations, test code, etc. Just let me know.

Sincerely,

Chris

**Comment by Avery-Dunn** [comment]
Thanks for the info about Clojure. After some discussion, we've decided to probably make those classes public in our next release, as well as check for other places where this issue might happen.

I don't have an ETA for that but it should be within the next few weeks, and I'll update this thread once it's available.

**Comment by chrisbetz** [comment]
Hi @Avery-Dunn,

thanks for sharing that decision, and I'm glad you decided that way.

No problem wrt no ETA, but thanks for the rough timeframe. Looking forward.

Have a nice weekend!

**Comment by Avery-Dunn** [comment]
Sorry for the delay on this, but these classes were made public in https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/504, and this was part of the recent [1.12.0 release](https://search.maven.org/artifact/com.microsoft.azure/msal4j/1.12.0/jar).

If the issue is still unresolved or if there are any related issues feel free to re-open this thread or open a new one.

**Comment by chrisbetz** [comment]
👍🏻 Thanks, @Avery-Dunn , I was successfully able to test it and now it's piece of cake to retrieve an access token using Clojure.
