### ISSUE TITLE
Vulnerabilities from transitive dependencies 

### ISSUE THREAD

**Issue by anumalasri** [AzureAD/microsoft-authentication-library-for-java#501]
Nimbus and Jackson dependencies from  'msal4j' (even latest version) have vulnerabilities. 

https://mvnrepository.com/artifact/com.microsoft.azure/msal4j/1.11.3

Can we get appropriate transitive dependencies and versions ?

**Comment by siddhijain** [comment]
Hello @anumalasri. Thanks for raising this. We are already looking into these issues and working on a fix. We will update you once the fix is released.

**Comment by anumalasri** [comment]
@siddhijain  .. do you have any ETA on when the fix will be available for us ??

**Comment by Avery-Dunn** [comment]
This issue was addressed in https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/502, and should be fixed as of the recent [1.12.0 release](https://search.maven.org/artifact/com.microsoft.azure/msal4j/1.12.0/jar).

If the issue is still unresolved or if there are any related issues feel free to re-open this thread or open a new one.

**Comment by anumalasri** [comment]
@Avery-Dunn  ...  Some of nimbus transitive dependencies still have vulnerable versions..

com.nimbusds:nimbus-jose-jwt:9.21. (https://nvd.nist.gov/vuln/detail/CVE-2022-21449) 
\--- com.nimbusds:oauth2-oidc-sdk:9.32
\--- com.microsoft.azure:msal4j:1.12.0

Can you please look into it ?
