### ISSUE TITLE
MSAL returns expired idToken when accessToken still valid

### ISSUE THREAD

**Issue by shaundsmith** [AzureAD/microsoft-authentication-library-for-java#568]
Observed in versions 1.12.0 and 1.13.3.

The idToken and accessToken have been configured by our AD administrator to have different expiration times. The idToken has the shorter expiration time. We have observed expired idTokens being returned when silently acquiring the tokens, due to the access token still being valid.

**Code Observations**
`IPublicClientApplication.acquireTokenSilently` will return the expired idToken as long as the accessToken is still valid.

This is due to `TokenCache.saveTokens` using the accessToken expiration timestamp as the cache expiration timestamp.
`TokenCache.getCachedAuthenticationResult` then reads the cache expiration time from the accessToken cache.
`AcquireTokenSilentSupplier.execute` then uses the results of `TokenCache.getCachedAuthenticationResult` to determine whether all tokens should be refreshed or not.

**Comment by Avery-Dunn** [comment]
Hello @shaundsmith : Could you describe your scenario a bit more? Is there a reason that the ID token is configured to expire sooner than access token? If an ID token expires before the access token, then that implies you can't trust the user is who they say they are but you can trust their claims about what they have access to, and I'm not sure where that would be necessary.

[Refresh tokens](https://learn.microsoft.com/en-us/azure/active-directory/develop/refresh-tokens) are mostly intended to pair with access tokens (and there are some scenarios where you don't even use ID tokens), which is why we just check the access token's details in the silent flow. I'm pretty sure that ID tokens are mainly just used when acquiring access tokens, and after that the expiry data doesn't really matter (though I wouldn't be surprised if some Azure service needed an unexpired ID Token for something).

**Comment by shaundsmith** [comment]
Hi @Avery-Dunn, apologies for the delayed response. We've been trying to trace the reason behind the difference between our access and ID token expiration times, and find out who has control over this functionality in the company.

Our use case is that we're authenticating with Azure AD in order to authenticate with an internal API. This internal API takes an access token and an ID token, and exchanges them for its own access token which we can use for future requests. In our instance, the internal access token expired and the AD ID token had expired, but the AD access token was still active due to a difference in the expiration times.

It sounds like this issue is misconfiguration on our side, and we can either force a refresh of the tokens or align the expiration times of the tokens. I'm happy to close this issue.

If you think it would be a worthwhile change, I can raise a PR to tweak the JavaDoc on `IClientApplicationBase.acquireTokenSilently` to explicitly state that the tokens are refreshed if the access token has expired - at the moment it just states 'tokens have expired'.

**Comment by Avery-Dunn** [comment]
Glad you got it sorted out, and thanks for the offer to tweak the docs! Feel free to make a PR, we'll review it and add it into our next release.
