### ISSUE TITLE
AADSTS53003 error on non azure linux VM

### ISSUE THREAD

**Issue by gan123** [AzureAD/microsoft-authentication-library-for-java#597]
Hi,
I have my code that runs fine on azure VM to get the AD token from our azure login. However it fails with the below error on a VM that is a simple plain RHEL7 linux.

MsalInteractionRequiredException: AADSTS53005: access has been blocked by conditional access policies. The access policy does not allow token issuance.

The scope I am using is User.Read. I passing in the username and passeword and calling acquireToken. I have also set the proxy and port as per our internal guidelines. Not sure what is missing here. Like i said, it works just fine on my local machine and on azure VMs.

Any help is appreciated!

Thanks.

**Comment by siddhijain** [comment]
@gan123 This error is coming from the token issuance service (ESTS) which is blocking the request due to the conditional access policy. You might have to contact your administrator to understand more.

AADSTS53003 | BlockedByConditionalAccess - Access has been blocked by Conditional Access policies. The access policy does not allow token issuance. If this is unexpected, see the conditional access policy that applied to this request in the Azure Portal or contact your administrator. For additional information, please visit troubleshooting sign-in with Conditional Access.

More information here https://learn.microsoft.com/en-us/azure/active-directory/develop/reference-aadsts-error-codes

**Comment by siddhijain** [comment]
Closing this as it is not msal4j issue. Please reopen this if there are any questions.
