### ISSUE TITLE
'account_type' not constant depending on library version / some headers

### ISSUE THREAD

**Issue by ypiel-talend** [AzureAD/microsoft-authentication-library-for-java#646]
Hi,

We have identified that in the authentication phase, there is a first call to "https://login.microsoftonline.com/common/userrealm/<user email>?api-version=1.0" that retrieve some public information about the given account. In those returned information, there is an attribute 'account_type' thant can be 'Managed' or 'Federated'.
This end point accept some headers like "x-client-VER" and "x-client-SKU".
It seems that the returned account_type depends on those 2 headers.

With MSal SKU header is set to "MSAL.Java" and VER the current version we use "1.11.2". The account is returned as 'Federated':
![2023-05-05_18-32](https://user-images.githubusercontent.com/29707101/236515766-bfb864cb-ce10-429f-a618-e152ebe3e0c6.png)
But then the grant type is "urn:ietf:params:oauth:grant-type:saml2-bearer":
![image](https://user-images.githubusercontent.com/29707101/236516097-8917ad2e-5d81-4b5d-a05b-cbf8333594a1.png)

But if I force them to "1.1.1" & "java" or remove them (like in Adal4j < 1.6.3) the acount we have is returned as 'Managed':
![image](https://user-images.githubusercontent.com/29707101/236516713-2d7d2b34-0345-4c5b-8d99-81b63f1ad259.png)

And it use a grant_type = password as we expect:
![image](https://user-images.githubusercontent.com/29707101/236516859-85ddfe11-5752-41a2-9331-61bb625c3e4c.png)

First, our code was based on Adal4J 1.1.1 and it was working well. Then we bump to Adal4J1.6.5 and after to MSal1.11.2. We didn't pay attention for different reasons, that it was not working anymore. We have this error with MSal:
Exception in thread "main" javax.naming.AuthenticationException: com.microsoft.aad.msal4j.MsalServiceException: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: 5cafb5ef-9e94-48f0-a67e-0396da613300
Correlation ID: 2b00d6fd-187f-44cb-9689-b9c8bccf63ce

We tried to understand, and as I explained before, some headers has been introduced in ADal4J 1.6.3 : https://github.com/AzureAD/azure-activedirectory-library-for-java/compare/1.6.2...1.6.3#diff-8f6e95afed2a7213b6972ec329405a10e7563d7054ee312d32820d3b25f737dfR133

and kept in MSal.

Would you have a lead on why our account is sometime returned as 'Federated' or 'Managed' dependeding those headers ?

Regards.

**Comment by siddhijain** [comment]
@ypiel-talend Your observation is right that when the returned account type from the common/userrealm endpoint, is Federated, msal4j converts the grant type to SAML https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/32c57511565cb46481de2fd91072e56cf1e44880/msal4j-sdk/src/main/java/com/microsoft/aad/msal4j/AcquireTokenByAuthorizationGrantSupplier.java#L107 otherwise it stays ROPC .

Coming to the question 'Would you have a lead on why our account is sometimes returned as 'Federated' or 'Managed' depending on those headers ?' -> The account type returned by the common/userrealm?api_version=1.0 endpoint depends on the Authorization header in the request. If the Authorization header contains a valid access token that was issued by an **external identity provider**, such as an on-premises Active Directory or another cloud-based identity provider, the account type will be returned as **federated**. If the Authorization header contains a valid access token that was issued by the **Azure AD tenant**, the account type will be returned as managed. The account type is determined by the authentication method used to obtain the access token. 

I will check why the account type is returned as managed in the absence of headers (prior to release 1.6.3). From what I got from the documentation, the common/realm endpoint will throw an error if headers (especially the Authorization header) are missing in the request.

In the meantime, can you share more logs so we can help you find out the reason for your exception?

**Comment by ypiel-talend** [comment]
Hello @siddhijain , thanks for your responsiveness; it is very much appreciated.

Here is full logs I have:
```
[ForkJoinPool.commonPool-worker-19] INFO com.microsoft.aad.msal4j.HttpHelper - [Correlation ID: null] Sent (null) Correlation Id is not same as received (null).
[ForkJoinPool.commonPool-worker-19] INFO com.microsoft.aad.msal4j.HttpHelper - [Correlation ID: null] Sent (null) Correlation Id is not same as received (null).
[ForkJoinPool.commonPool-worker-19] INFO com.microsoft.aad.msal4j.WSTrustResponse - Found token of type: urn:oasis:names:tc:SAML:1.0:assertion
[ForkJoinPool.commonPool-worker-19] ERROR com.microsoft.aad.msal4j.ConfidentialClientApplication - [Correlation ID: 62133dae-8bed-49fc-9fc0-fc45864089bd] Execution of class com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier failed.
com.microsoft.aad.msal4j.MsalServiceException: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: 8d488c11-a50c-4dd9-886e-2228905f0f00
Correlation ID: 62133dae-8bed-49fc-9fc0-fc45864089bd
Timestamp: 2023-05-09 08:21:35Z
	at com.microsoft.aad.msal4j.MsalServiceExceptionFactory.fromHttpResponse(MsalServiceExceptionFactory.java:45)
	at com.microsoft.aad.msal4j.TokenRequestExecutor.createAuthenticationResultFromOauthHttpResponse(TokenRequestExecutor.java:96)
	at com.microsoft.aad.msal4j.TokenRequestExecutor.executeTokenRequest(TokenRequestExecutor.java:37)
	at com.microsoft.aad.msal4j.AbstractClientApplicationBase.acquireTokenCommon(AbstractClientApplicationBase.java:128)
	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:63)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:71)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:20)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Exception in thread "main" javax.naming.AuthenticationException: com.microsoft.aad.msal4j.MsalServiceException: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: 8d488c11-a50c-4dd9-886e-2228905f0f00
Correlation ID: 62133dae-8bed-49fc-9fc0-fc45864089bd
Timestamp: 2023-05-09 08:21:35Z
	at org.talend.ms.crm.odata.authentication.OAuthStrategyImpl.getHttpClientFactory(OAuthStrategyImpl.java:65)
	at org.talend.ms.crm.odata.DynamicsCRMClient.init(DynamicsCRMClient.java:135)
	at org.talend.ms.crm.odata.DynamicsCRMClient.<init>(DynamicsCRMClient.java:124)
	at FailingMSAL.main(FailingMSAL.java:41)
```

**Comment by bgavrilMS** [comment]
Hi @ypiel-talend 

What is your top level API? Are you calling `AcquireTokenByIntegratedWindowsAuth` or `AcquireTokenByUsernamePassoword`?

the MSAL libraries identify themselves to the service (AAD). In some cases like this one, AAD will change behavior when they see an MSAL library of a certain version, as it knows that it supports certain features. This was done because in the past, when AAD wanted to make changes, it broke 3rd party SDKs.

In this particular case, what is happening is that normally the user is managed, i.e. I assume your users are in AAD only, not in some local Active Directory, federated to AAD. Pls correct me if I am wrong. 

Normally, Integrated Windows Authentication doesn't work with Managed accounts and Username/Password flow is different for managed users than for federated users. 

If however you enable [seamless SSO](https://learn.microsoft.com/en-us/azure/active-directory/hybrid/connect/how-to-connect-sso), the users will be reported as Federated and Integrated Windows Auth will work.

**Comment by ypiel-talend** [comment]
Hi @bgavrilMS, the issue seem to come before those calls, when it calls common/userrealm endpoint. Indeed, before the account was returned as 'Managed' when headers were not given. Since headers are given, it is returned as federated. 
Here is a screenshot of the account:
![image](https://github.com/AzureAD/microsoft-authentication-library-for-java/assets/29707101/70099605-9788-4530-9a77-8e865a8c75e7)
Should 'User type = Member' be always returned as 'Managed' no ?

Regards.

**Comment by bgavrilMS** [comment]
It depends ... If your organization enabled Seamless SSO feature https://learn.microsoft.com/en-us/azure/active-directory/hybrid/connect/how-to-connect-sso then the account comes up as `Federated`. Seamless SSO is a a feature to make AAD behave more like ADFS, without actually having users in ADFS. It helps migrate users from ADFS into AAD without having to change app code. 

If the user type is "Managed" then: 

- Username / Password flow will use the standard OAuth mechanism
- Integrated Windows Auth will fail 

If the user is Federated, then both Username / Password and Integrated Windows Auth should use a SAML flow. I think this is what's happening here. 

Question is - what are you trying to do ? In public client apps we recommend using AcquireTokenInteractive. For SSO with Windows, MSAL Java will soon be able to use a better approach, based on PRT.
