### ISSUE TITLE
Error compiling: .AcquireTokenByAuthorizationGrantSupplier failed

### ISSUE THREAD

**Issue by albertoRamon** [AzureAD/microsoft-authentication-library-for-java#657]
(mvn install on Ubuntu on Win11)
```
openjdk 11.0.19 2023-04-18
OpenJDK Runtime Environment (build 11.0.19+7-post-Ubuntu-0ubuntu120.04.1)
OpenJDK 64-Bit Server VM (build 11.0.19+7-post-Ubuntu-0ubuntu120.04.1, mixed mode, sharing)
```
```
Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.0:jar (attach-javadocs) on project msal4j: MavenReportException: Error while generating Javadoc:

Exit code: 1 - error: --add-modules ALL-MODULE-PATH can only be used when compiling the unnamed module
```

` [ForkJoinPool.commonPool-worker-3] ERROR com.microsoft.aad.msal4j.PublicClientApplication - [Correlation ID: a6f29e6a-d1ae-4e18-97cd-3c3925a8d7a0] **Execution of class com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier failed.**
com.microsoft.aad.msal4j.MsalThrottlingException: Request was throttled according to instructions from STS. Retry in 987 ms.
        at com.microsoft.aad.msal4j.HttpHelper.checkForThrottling(HttpHelper.java:116)
        at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:37)
        at com.microsoft.aad.msal4j.OAuthHttpRequest.send(OAuthHttpRequest.java:33)
        at com.microsoft.aad.msal4j.TokenRequestExecutor.executeTokenRequest(TokenRequestExecutor.java:33)
        at com.microsoft.aad.msal4j.AbstractClientApplicationBase.acquireTokenCommon(AbstractClientApplicationBase.java:128)
        at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:63)
        at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:69)
        at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:18)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)`

**Comment by Avery-Dunn** [comment]
Hello @albertoRamon : I see you have two error messages: 
- MavenReportException: Error while generating Javadoc
- MsalThrottlingException: Request was throttled according to instructions from STS.

Are they related, or are you raising two separate issues here?

For the Maven issue I'm not really sure what could be going on or how it's related, but the issue from MSAL Java is pretty straightforward: under certain circumstances requests to the token service may be throttled, and the error message is suggesting you try again after a certain amount of time (looks like a suggested 1 second retry time).

Requests could be throttled for a number of reasons, but the most common is too many requests in a certain amount of time. Could you describe your use case a bit more? How many requests are you making, and are you making use of [MSAL Java's in-memory cache](https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Acquiring-Tokens#msal4j-caches-tokens) to avoid making repetitive token calls?

**Comment by albertoRamon** [comment]
@Avery-Dunn 
It Is when compile: mvn install

**Comment by Avery-Dunn** [comment]
What do you mean by that? Is what you posted all one error, like you're seeing that `ERROR com.microsoft.aad.msal4j.PublicClientApplication ...` stuff when building your application with Maven?

Are you using MSAL Java in some tests that get executed when you build your application? I'm not really sure how else you'd be seeing those sorts of errors during a build

And could I get some of the info I asked about in my other comment (how many requests are you making, are you using the cache, etc.)

**Comment by albertoRamon** [comment]
yes, this error is when Build the library Msal4j
- Git clone . . .
- cd . . .
- mvn install

**Comment by Avery-Dunn** [comment]
Wait, you're trying to build the msal4j package (the code in this repository)? If so I'm still not sure why you're getting a 'throttling' error, but many of our tests will certainly fail outside of our internal dev environments.

Is there a reason you're building our package rather than getting it from Maven? https://mvnrepository.com/artifact/com.microsoft.azure/msal4j

If you really want to build it yourself, I guess you can try skipping the tests and just compiling the package. This might work, but I'd still recommend getting an already built package from Maven: `mvn install -Dmaven.test.skip=true`

**Comment by albertoRamon** [comment]
Yes. We are trying to build your package because we are not sure of there is some issue with our java version

This is to replace the old JDBC jar file in JIRA server.
JIRA manual recommended compile the JDBCs in the the own server

Already try to skip test. But didn't work

**Comment by Avery-Dunn** [comment]
By "didn't work" do you mean that the tests weren't getting skipped? Because if the tests are skipped, then no code should run and I don't see how it's possible for an error like that 'MsalThrottlingException' to show up. If the tests are skipped, then could you post the error you got?

As for the Java version, we compile it with Java 8, and you might be able to compile it with Java 11 but I'm not sure.

Also, you mention JDBC: are you trying to compile all of JDBC's dependencies (like msal4j) locally, then use them to compile JDBC? If so, could you post a link to where that was recommended? Because I'd be surprised if that was a recommended solution for something.

**Comment by albertoRamon** [comment]
I will close the ticket, 
perhaps compile the project, wont solve anything

(thanks in any way_
