### ISSUE TITLE
Showcase CAE Auth Context in a sample

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-java#665]
CAE Auth Context has samples in .NET and NodeJS, but not in Java. This is being asked for by customers.

See https://learn.microsoft.com/en-us/azure/active-directory/develop/developer-guide-conditional-access-authentication-context#code-samples

**Comment by linkaiyu** [comment]
customer has large number of java app. They security governing team at enterprise level is trying to push AD adoption strategy forward but are blocked due to lack of samples for java. The governing team at enterprise level has to set policy together rigorous documentation and sample apps for the teams to start reviewing and implementing so having a sample app is a must before any progress can be made.

**Comment by bgavrilMS** [comment]
@linkaiyu - what is top priority here? Web app or web api sample? I would presume web api?

**Comment by linkaiyu** [comment]
@bgavrilMS , ideally they want the whole application (web app and web api) together so that they can list it as the app template to their business units. is the implementation of the conditional access in the web api? if so, the web app should be the same with the .net one if I understand it correctly.

**Comment by bgavrilMS** [comment]
Sample here: https://github.com/Azure-Samples/ms-identity-msal-java-samples/tree/main/3-java-servlet-web-app/1-Authentication/sign-in-auth-context
