### ISSUE TITLE
Latest release `1.13.9` has no git tag nor GitHub release page

### ISSUE THREAD

**Issue by martokarski** [AzureAD/microsoft-authentication-library-for-java#680]
In the past you were creating tags for every version and posted a summary of a release in the "releases" section. The latest release lacks those elements. I'm not even sure if the branch https://github.com/AzureAD/microsoft-authentication-library-for-java/tree/avdunn/1.13.9-release correctly points to the released version.

Could you add those elements for the `1.13.9` release?

Example for the `1.13.8` release:
* https://github.com/AzureAD/microsoft-authentication-library-for-java/releases/tag/v1.13.8
* https://github.com/AzureAD/microsoft-authentication-library-for-java/tree/v1.13.8

**Comment by Avery-Dunn** [comment]
Sorry for the confusion there. We usually create the release tag after it publicly appears in the Maven central repository, but due to some build issues last week it took a couple days to show up and I simply forgot for this one.

I've just made the new tags for the release, with the changelog summary and links to the relevant PRs: https://github.com/AzureAD/microsoft-authentication-library-for-java/releases/tag/v1.13.9

**Comment by martokarski** [comment]
Thank you @Avery-Dunn for the quick response and action!
