### ISSUE TITLE
Change log level from `info` to `debug` for `AcquireTokenSilentSupplier`

### ISSUE THREAD

**Issue by durimkryeziu** [AzureAD/microsoft-authentication-library-for-java#751]
In one of the projects I'm working on, we're using this library as a transitive dependency of the `azure-identity` and my logs are full of these log statements. Could this be changed to `debug` level, please?

https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/000f4c9baa0353b18cf95880c882134183564fea/msal4j-sdk/src/main/java/com/microsoft/aad/msal4j/AcquireTokenSilentSupplier.java#L112

**Comment by Avery-Dunn** [comment]
Hello @durimkryeziu : I don't think there would be any issues with lowering the log level, it does seem like there could be a lot of these messages. 

We'll look into getting this fixed in an upcoming release. However, if you're seeing these MSAL Java messages because you're using an Azure SDK then our fix will only appear when they update to use the new version, and we don't have control over their release schedule.

**Comment by Avery-Dunn** [comment]
As of the recent 1.14.1 release, this log should now be at the 'debug' level instead of 'info'

**Comment by durimkryeziu** [comment]
Hi @Avery-Dunn, thanks for making the required change! Yes, I am aware that it doesn't mean that it will be included in the Azure SDK immediately and that you don't have control over their release schedule, so all good 👍
