### ISSUE TITLE
[Bug] Managed Identity App sends POST request instead of GET on CloudShell

### ISSUE THREAD

**Issue by g2vinay** [AzureAD/microsoft-authentication-library-for-java#771]
### Library version used

14.4.2-beta

### Java version

JDK 17

### Scenario

ManagedIdentityClient - managed identity

### Is this a new or an existing app?

None

### Issue description and reproduction steps

Managed Identity App sends a POST request instead of a GET request for cloud shell case.
This causes service side error of missing `aud` parameter in the request when sent via pluggable Netty Client.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by Avery-Dunn** [comment]
Per some discussions, closing as not an issue. Many of the other services explicitly document using GET requests ([Azure VM](https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-http), [Service Fabric](https://learn.microsoft.com/en-us/azure/service-fabric/how-to-managed-identity-service-fabric-app-code#acquiring-an-access-token-using-rest-api), etc.) but Cloud Shell does not (though a simple curl on the Cloud Shell endpoint using GET shows that it can get a token).

However, some Cloud Shell folks have said to use POST since "it's more robust and handles the extra options such as the ssh-cert token type, but for simple token requests GET would also work." MSAL Python also has been using POST in production for some time, so this likely not an issue for Cloud Shell (though the others will use GET).
