### ISSUE TITLE
[Bug] MSAL4J interactive flow fails with Chrome version 123

### ISSUE THREAD

**Issue by KodarLiteIbland** [AzureAD/microsoft-authentication-library-for-java#801]
### Library version used

1.14.3

### Java version

Amazon Corretto 8 version 1.8.0_392

### Scenario

PublicClient (AcquireTokenInteractive, AcquireTokenByUsernamePassword)

### Is this a new or an existing app?

The app is in production, and I have upgraded to a new version of MSAL

### Issue description and reproduction steps

1. Make sure Google Chrome is updated to version 123
2. Set Google Chrome as default browser
3. Make sure the app registration used has http://localhost as redirect URI in Desktop and Mobile platform in Entra ID
4. Make a simple call that uses default browser to interactively acquire token from localhost, like the snippet below
5. Complete login process until redirected back to http://localhost

### Relevant code snippets

```csharp
Reproducible with the example in https://learn.microsoft.com/en-us/entra/msal/java/getting-started/acquiring-tokens-interactively

PublicClientApplication publicClientApplication =
        PublicClientApplication
                .builder(CLIENT_ID)
                .authority(AUTHORITY)
                .build();

InteractiveRequestParameters parameters = InteractiveRequestParameters
        .builder(new URI("http://localhost"))
        .scopes(scope)
        .build();

IAuthenticationResult result = publicClientApplication.acquireToken(parameters).join();
```

### Expected behavior

Expected behavior that Google Chrome, after login process, connects to localhost and the PublicClientApplication is able to acquire the token. 

This used to work up to Chrome version 122, but since version 123 Chrome fails to connect to the localhost address - there is an additional preflight request to the same address in the newer version that succeeds but the actual request fails.

If you think this is a problem with Chrome rather than MSAL4J, please comment and, I suppose, close issue.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

### Solution and workarounds

1. Obviusly: Changing default browser to, e.g., Edge or Firefox fixes problem.

2. For Google Chrome: if started with 

chrome -args --disable-features=PrivateNetworkAccessForNavigations,PrivateNetworkAccessForNavigationsWarningOnly

login works as expected

**Comment by Avery-Dunn** [comment]
Hello @KodarLiteIbland : I'm not able to reproduce your issue. 
- I had been on Chrome version 122, and using the code you posted and two different users I could get a token
- I then restarted chrome and updated to 123.0.6312.59, and could still get tokens without issue

Is there any specific error message from MSAL or Chrome?

Since disabling that PrivateNetworkAccessForNavigations feature seems to resolve it, then the issue is probably with the security settings in Chrome and some setting may have become more strict after the update.

**Comment by KodarLiteIbland** [comment]
Hi @Avery-Dunn 
Interesting that you could not reproduce the error, would it help if I paste full code for a reproducing sample? 
Chrome reports ERR_CONNECTION_REFUSED, after which MSAL gets MsalClientException "No authorization code was returned from the server".

**Comment by KodarLiteIbland** [comment]
BTW, there are some open issues for Chromium project with similar issues in other products as well, so it might be that this is addressed in future updates

https://issues.chromium.org/issues?q=status:open%20PrivateNetworkAccessForNavigations

**Comment by Avery-Dunn** [comment]
The full code could help, but I don't think this is an MSAL issue. What you've already posted is pretty much all of the browser interaction that MSAL has for the interactive flow, and as you mention there are reports of similar issues in a variety of scenarios. 

In particular at that link there is issue [330594669](https://issues.chromium.org/issues/330594669), which pretty much describes your issue exactly: upgrade to 123, redirect to localhost, get ERR_CONNECTION_REFUSED. That issue is about gcloud, and mentions that it's affection Python clients also, so it's very unlikely we coincidentally have an unrelated bug only in MSAL Java.

I guess I'll leave this open for now in case anything changes in the next few days, but this is probably not an MSAL issue and there's not much we can recommend other than that workaround you've already found.

**Comment by KodarLiteIbland** [comment]
Hi @Avery-Dunn 
Sorry for late answer, but yes, the reproducing sample was more or less those lines + a little setup, so probably not relevant.
Chromium issue issue [330594669](https://issues.chromium.org/issues/330594669) was already reported fixed in Chrome Canary, and I can confirm that the Interactive Flow works again in Canary too. So apparently this was an unwanted side-effect that will be removed from official Chrome soon, and (hopefully) not at all to other Chromium based browsers like Edge.
You can decide whether to close issue now, or when official Chrome is updated. Thanks for your time!

**Comment by Avery-Dunn** [comment]
Glad to hear it's working in that Canary version, thanks for testing it out! If you run into any other issues, feel free to re-open this thread or open a new one.
